### ISSUE TITLE
Pushing tagged images doesn't work for the second tag with `multiarch: false`

### ISSUE THREAD

**Issue by powerc9000** [basecamp/kamal#561] opened 2023-11-01 21:40 UTC
If you have

```
builder:
    multiarch: false
```

when running `kamal deploy --version=qa` kamal eventually tries to run

```
docker build -t <repo-url>:qa -t <repo-url>:latest --label service="service-name" --file Dockerfile . && docker push <repo-url>:qa && docker push <repo-url>:latest
```

The first `docker push` works and pushes an image. But the second push errors with `tag does not exist: <repo-url>:latest`. This seems related to https://github.com/docker/setup-buildx-action/issues/116 

This doesn't happen with multiarch builds or when a builder cache is used.

**Comment by djmb** [comment] 2024-03-06 12:02
https://github.com/docker/setup-buildx-action/issues/116 looks like a different issue, where the tags are not available at all.

I've tried to reproduce this but I can't - running `kamal deploy` repeatedly with a version in the integration tests (which use the `multiarch: false` setting succeeds.

**Comment by djmb** [comment] 2024-09-30 07:32
Going to close this one as the `multiarch` option has been removed in Kamal 2.

**Closed by djmb** 2024-09-30 07:32 UTC
Labels: Builder
