### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by SebSwan** [basecamp/kamal#662] opened 2024-01-24 23:05 UTC
I'm stuck around this error since a moment. I'm new on Kamal & Docker.

i use:
ruby  3.0.1
rails  6.1.7.1

i get this error when i use 'kamal setup'

and in production.rb
`config.require_master_key = false`

Dockerfile
```

# Precompile bootsnap code for faster boot times
RUN bundle exec bootsnap precompile app/ lib/


# Precompiling assets for production without requiring secret RAILS_MASTER_KEY
RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile


# Final stage for app image
FROM base
```

```
------
Dockerfile:39
--------------------
  37 |     
  38 |     # Precompiling assets for production without requiring secret RAILS_MASTER_KEY
  39 | >>> RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile
  40 |     
  41 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile" did not complete successfully: exit code: 1
```
i used `EDITOR="code --wait" rails credentials:edit   ` to be sure to have clean credentials.

https://www.reddit.com/r/rails/comments/191n2cl/error_doing_a_kamal_deploy/
https://discuss.rubyonrails.org/t/new-rails-7-1-2-bootstrap-project-fails-to-precompile-in-docker/84292

**Comment by tahirwaseer** [comment] 2024-02-02 10:20
Try increasing the memory of the instance if it's a smaller instance. 
I've had some issues with the `precompile` step. It kept falling without any explicit error and after much debugging it was running out of memory during the precompile step.

**Comment by tahirwaseer** [comment] 2024-02-02 12:03
This can be relevant. 
https://stackoverflow.com/questions/77725755/segmentation-fault-during-rails-assetsprecompile-on-apple-silicon-m3-with-rub

**Comment by Set27** [comment] 2024-02-07 15:58
@tahirwaseer it's a bit strange, that for run application with docker, I have to wait for ruby 3.3.1

**Comment by djmb** [comment] 2024-03-04 10:48
Duplicate of #624

**Closed by djmb** 2024-03-04 10:48 UTC
