### ISSUE TITLE
tailwind styles do not update with latest tag

### ISSUE THREAD

**Issue by n1xn** [basecamp/kamal#641] opened 2024-01-10 23:02 UTC
When using a single tag for the container image new introduced tailwindcss styles do not apply / get added to the styles.
Using sha fixes this issue. 

**Dockerfile**
```
RUN bundle exec bootsnap precompile app/ lib/
RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile

FROM base
```

**config/deploy.yml**
```
asset_path: /rails/public/assets
```

**.github/workflows/ci.yml**
```
      - name: build & push docker image to ghcr.io
        uses: docker/build-push-action@v5
        with:
          context: ./rails
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

      - name: deploy with Kamal
        working-directory: ./rails
        run: kamal deploy --skip-push -vvvv
        env:
          GITHUB_CONTAINER_REGISTRY_TOKEN: ${{ github.token }}
          VERSION: ${{ github.sha }} # -> latest doesn't update assets properly
```

**Comment by mhenrixon** [comment] 2024-03-06 08:34
I think you are mistaken, @n1xn! From what I can see, this problem is caused by a filename sort order. 

Rails seem to pick the first available, so if `application-olddigest.css` is sorted before `application-newdigest.css,` we keep seeing the old CSS.

I will turn this off for now as this behavior is unacceptable.

**Comment by mhenrixon** [comment] 2024-03-06 15:09
I managed to sort out the other sprockets issues I had. I will attempt to put back the `asset_path: /rails/public/assets` and see if this is still a problem.

**Comment by djmb** [comment] 2024-03-06 15:10
If this is a Sprockets specific issue, is this the fix here - https://github.com/basecamp/kamal/pull/627?

**Comment by mhenrixon** [comment] 2024-03-06 15:50
That would be the issue @djmb, and I am guessing @n1xn is also using sprockets and that this specific issue is related to the sprockets manifest: https://github.com/basecamp/kamal/issues/626

I finally got around to fixing propshaft and it does not have this issue!

**Comment by djmb** [comment] 2024-03-06 15:52
Thanks @mhenrixon. I'll close this now, but feel free to re-open @n1xn if there's something else going on.

**Closed by djmb** 2024-03-06 15:52 UTC
