### ISSUE TITLE
ERROR (Module::DelegationError): Kamal::Commands::Accessory#hosts delegated to accessory_config.hosts, but accessory_config is nil

### ISSUE THREAD

**Issue by melashu** [basecamp/kamal#651] opened 2024-01-16 09:30 UTC
Hello Everyone,

Can anyone assist me I am new to `Kamal` and struggling a lot to deploy my app using it. I appreciate any help
I have been blocked for 5 days with this error 

I have done research, and watching videos but I can't fix this issue
I am using `Rails 7.1.2`
Here is my deploy.yml 
```yml
service: cliptill_production
image: melashu/cliptill 
env:
  clear:
    DB_HOST: x.x.x.x
    POSTGRES_USER: cliptill_production
  secret:
    - RAILS_MASTER_KEY
    - DB_NAME
    - DB_USERNAME
    - DB_PASSWORD
    - KAMAL_REGISTRY_PASSWORD
servers:
  web:
    hosts:
      - x.x.x.x
registry:
  username: melashu 
  password:
    - KAMAL_REGISTRY_PASSWORD
accessories:
  db:
    image: postgres:latest
    host: x.x.x.x
    port: 5432
    env:
      clear:
        POSTGRES_USER: $DB_USERNAME
        POSTGRES_DB: $DB_NAME
        POSTGRES_PASSWORD: $DB_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
```

When I run `kamal setup` I get the error 
![image](https://github.com/basecamp/kamal/assets/30173722/d3f8e6e9-b01f-41d3-b97b-7ab7c2c75c5a)

When I run `kamal accessory reboot postgres `, I got this below 

![image](https://github.com/basecamp/kamal/assets/30173722/6c11d5af-ebbf-493b-a9fc-bb4c54f20626)

Thank you for your kind support

**Comment by acidtib** [comment] 2024-01-16 20:40
from the error it seems like Rails app is not able to connect to the database, most likely caused by firewall restrictions, port `5432` (postgres) cant be reached, you can use your server providers firewall service, if they have one, or use ufw on the server `ufw allow 5432`, another option if your running everything one one server is to use docker networks and call the service by hostname instead of the ip address

**Comment by arpadlukacs** [comment] 2024-03-05 20:28
I think it should work if you put them into the same private network, see here: https://nts.strzibny.name/deploying-rails-single-server-kamal/

**Comment by djmb** [comment] 2024-03-06 15:15
Closing this as it doesn't look like an issue with Kamal

**Closed by djmb** 2024-03-06 15:15 UTC
